# Tensor的创建

In [2]:
import torch

a = torch.Tensor([[1, 2], [3, 4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
a = torch.Tensor(2, 2)
# 只指定size不指定值，每次的值都不一样，是随机的，或者说就是相应内存地址中原本的值
print(a)

tensor([[4.0000e+00, 4.5914e-41],
        [0.0000e+00, 0.0000e+00]])


In [4]:
a = torch.Tensor(((2, 2), (2, 2)))
print(a)
print(a.dtype)

tensor([[2., 2.],
        [2., 2.]])
torch.float32


# Tensor 的属性

In [5]:
# 用GPU进行处理
dev = torch.device('cuda:0')
a = torch.tensor([2, 2], dtype=torch.float32, device=dev)
print(a)

tensor([2., 2.], device='cuda:0')


In [6]:
i = torch.Tensor([[0, 1, 2], [0, 1, 2]])
v = torch.Tensor([1, 2, 3])
a = torch.sparse_coo_tensor(i, v, [4, 4], dtype=torch.float32, device=dev)
b= a.to_dense()
print(a)
print(b)

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1., 2., 3.]),
       device='cuda:0', size=(4, 4), nnz=3, layout=torch.sparse_coo)
tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


# Tensor 中的原位操作（in-place）
例如：
torch.sum_()

其实就是不占用的新的内存，在原来的内存地址上进行操作

# Tensor的广播机制
就是当tenser的shape不一样的时候，如果相加，会自动进行自动补齐，但是要满足“右对齐”：从右往左看，每一位上的值要么有1要么相等，如果维度不够的，用1补齐

In [7]:

a = torch.rand(2, 2)
b = torch.rand(1, 2)
c = a + b
print(a)
print(b)
print(c)
print(c.shape)

tensor([[0.2373, 0.9350],
        [0.8477, 0.4104]])
tensor([[0.4785, 0.9962]])
tensor([[0.7158, 1.9312],
        [1.3262, 1.4066]])
torch.Size([2, 2])


In [8]:
a = torch.rand(1, 2, 4, 3)
b = torch.rand(1, 3)
c = a + b
print(a)
print(b)
print(c)
print(c.shape)

tensor([[[[0.1068, 0.6422, 0.9731],
          [0.1456, 0.7996, 0.7660],
          [0.1113, 0.3376, 0.6956],
          [0.7478, 0.6095, 0.6693]],

         [[0.9000, 0.1734, 0.5806],
          [0.5083, 0.7554, 0.7050],
          [0.2962, 0.0287, 0.4188],
          [0.2682, 0.3925, 0.1323]]]])
tensor([[0.5158, 0.4086, 0.6542]])
tensor([[[[0.6226, 1.0508, 1.6272],
          [0.6614, 1.2082, 1.4202],
          [0.6271, 0.7462, 1.3498],
          [1.2636, 1.0181, 1.3235]],

         [[1.4158, 0.5820, 1.2347],
          [1.0241, 1.1640, 1.3592],
          [0.8120, 0.4373, 1.0729],
          [0.7840, 0.8011, 0.7864]]]])
torch.Size([1, 2, 4, 3])


# tensor 中取整，取余

In [20]:
a = torch.rand(2, 2) * 10
print(a)
print(a.floor())  # 向下取整
print(a.ceil())  # 向上取整
print(a.round())  # 四舍五入
print(a.trunc())  # 取整数部分
print(a.frac())  # 取小数部分
print(a%2)  # 取余数
b = torch.tensor([[2, 3], [4, 5]], dtype=torch.float32)
## 以下两个用法可以参考文档：
## https://pytorch-cn.readthedocs.io/zh/latest/package_references/torch/
print(torch.fmod(a, b))  # 取余数，a是被取余数， 结果的正负号与a里面的值相同
print(torch.remainder(a, b))  # 取余数，a是被取余数， 结果的正负号与b里面的值相同

tensor([[5.9712, 5.8541],
        [2.6980, 3.2548]])
tensor([[5., 5.],
        [2., 3.]])
tensor([[6., 6.],
        [3., 4.]])
tensor([[6., 6.],
        [3., 3.]])
tensor([[5., 5.],
        [2., 3.]])
tensor([[0.9712, 0.8541],
        [0.6980, 0.2548]])
tensor([[1.9712, 1.8541],
        [0.6980, 1.2548]])
tensor([[1.9712, 2.8541],
        [2.6980, 3.2548]])
tensor([[1.9712, 2.8541],
        [2.6980, 3.2548]])
